version: "3.7"

services:
  director:
    build:
      context: ./app
      target: Development
    image: pkeech/docker-celery-director-demo:dev
    volumes:
      - ./app/src:/app
    ports:
      - 8083:8083

  redis:
    build:
      context: ./DB
      target: Production
    image: pkeech/docker-celery-director-demo-rd:latest
    volumes:
      - Redis_Director_Data:/data

volumes:
  Redis_Director_Data: